#!/usr/bin/env sh
#
# A rofi powered menu to execute power related action.
# Uses: amixer mpc poweroff reboot rofi rofi-prompt

power_off=' Shutdown'
reboot=' Reboot'
lock=' Lock'
suspend=' Suspend'
log_out=' Logout'

chosen=$(printf '%s;%s;%s;%s;%s\n' "$power_off" "$reboot" "$lock" "$suspend" \
                                   "$log_out" \
    | rofi -theme-str "#listview {lines: 5; }"\
           -dmenu \
           -sep ';' \
           -selected-row 1.5\
           -fixed-num-lines\
           -eh 2)

case "$chosen" in
    "$power_off")
        poweroff
        ;;

    "$reboot")
        reboot
        ;;

    "$lock")
        swaylock -f
        ;;

    "$suspend")
        # Pause music and mute volume before suspending.
        playerctl stop
        amixer set Master mute
        # TODO Add your suspend command.
        ;;

    "$log_out")
        hyprctl dispatch exit
        ;;

    *) exit 1 ;;
esac
