#!/usr/bin/env sh
#
# A rofi powered menu to execute power related action.
# Uses: amixer mpc poweroff reboot rofi rofi-prompt

power_off=' Shutdown'
reboot=' Reboot'
lock=' Lock'
suspend=' Suspend'
log_out=' Logout'

chosen=$(printf '%s\n%s\n%s\n%s\n%s' "$power_off" "$reboot" "$lock" "$suspend" \
                                   "$log_out" \
    | wofi --dmenu)

case "$chosen" in
    "$power_off")
        poweroff
        ;;

    "$reboot")
        reboot
        ;;

    "$lock")
        swaylock -f
        ;;

    "$suspend")
        # Pause music and mute volume before suspending.
        playerctl stop
        amixer set Master mute
        systemctl suspend
        ;;

    "$log_out")
        hyprctl dispatch exit
        ;;

    *) exit 1 ;;
esac
